### ISSUE TITLE
希望加入代码高亮

### ISSUE THREAD

**Issue by tufu9441** [icylogic/maupassant-hexo#10]
如题，希望加入那种黑色背景的代码高亮效果，效果应该不错。

**Comment by tufu9441** [comment]
我自己通过加载highlight.js以及它的CSS实现了（但需要在Hexo的_config.yml将highlight选项设置为false），因为若不加载highlight.js只用Hexo自带的代码高亮功能的话一直没能看到预期的效果。样式用的是monokai_sublime。

**Comment by liuchungui** [comment]
请问怎么加载的啊
